#Префикс
Prefix: '&f[&cOreFinder&f] '
#Сообщение когда вы обнаружили ресурсы
formatfindmessage: 'Вы нашли &e%type%'
#Сообщение когда вы не обнаружили ресурсы
formatnofindmessage: 'Вы нечего не нашли :('
#Диапазон обнаружения на которой кирка будет сканировать блоки
#Не советую ставить менше 4
range: 7

#Работоспособность 
working:
  #Будет ли искать алмазная кирка - алмазную руду
  DIAMOND_PICKAXE: true
  #Будет ли искать деревяная кирка - угольную руду
  WOOD_PICKAXE: true
  #Будет ли искать железная кирка - железную руду
  IRON_PICKAXE: true
  #Будет ли искать золотая кирка - золотую руду
  GOLD_PICKAXE: true